---
- name: ubuntu 16 ami
  ec2_ami_find:
    name:       "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"
    owner:      099720109477
    sort:       name
    sort_order: descending
    sort_end:   1
  register: ami_find
