---
- name: Terminate Simple Web Application Stack
  hosts: localhost

  connection: local

  vars:
    - role: web

  vars_files:
    - ./vars/common.yml

  roles:
    - ec2-terminate
    - elb-terminate
